### ISSUE TITLE
Prevent accidental/malicious project deletion

### ISSUE THREAD

**Issue by cathysarisky** [alan412/ev3hub#58]
Thank you for EV3HUB!  I'm looking forward to using the beta.ev3hub.com tools with my team this season.  

It would be /really really really/ nice to have a way to somehow prevent a project from being permanently deleted.  I love the kids on my team, but sometimes they click first and read second.  And your average 9-13 year old gets into "rage quit" mode at least once per season.

I see several ways to do this, any of which would prevent a catastrophic deletion:
-Multiple users on a project, with variable access levels (commit vs administer?)
-Have a separate password or require an email confirmation to delete a project (if the team is using the coach's email, this makes it impossible for them to serious screw the team up).
-Don't have project deletion be permanent (or don't have it be permanent until some length of time has passed)

In theory, I could reconstruct the team's work by finding a kid with a recent download, but for kids working on school computers or library computers, anything downloaded may be gone when the student logs out.

Thanks!

**Comment by alan412** [comment]
Remove Project currently requires a password (just like you suggest) and
for exactly the reason you suggest.   Can you please create a test project
and then make sure it requires the password?  (ie, leave the password blank
and make sure it doesn't delete it.)

**Comment by cathysarisky** [comment]
It does require a password, but that's the password that is needed to login.  Unless I never give the kids access unless I type the password, they've got that password.  Does that make sense?  I suggest more protection that the same password used to login, because the multiple kids using the account all need that password.

**Comment by alan412** [comment]
Ah.  Got it.   I hadn't thought about that possibility.    Ideally I would
like to put projects in a "will be deleted in n days" that can be
"restored".    Putting it on my list to work on.

**Comment by cathysarisky** [comment]
Thanks!

Dr. Catherine Sarisky
Associate Professor and Chair
Chemistry Department, Roanoke College
540-375-2438
Sarisky@roanoke.edu<mailto:Sarisky@roanoke.edu>


On Aug 13, 2018, at 12:13 PM, Alan Smith <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah. Got it. I hadn't thought about that possibility. Ideally I would
like to put projects in a "will be deleted in n days" that can be
"restored". Putting it on my list to work on.

**Comment by alan412** [comment]
Not live quite yet, because I need to do more testing before I push the new release.   I'll comment here when it is pushed.

**Comment by alan412** [comment]
Now it is live.
